<?php
return array(
	'message' => 'message/index',
	'changepw' => 'profile/changepw',
	'unlike' => 'profile/unlike',
	'like' => 'profile/like',
	'unblock' => 'profile/unblock',
	'block' => 'profile/block',
    'delvisit' => 'profile/delvisit',
    'visitorload' => 'profile/visitorload',
    'visitor' => 'profile/visitor',
    'online' => 'profile/online',
    'delete' => 'profile/delete',
    'set' => 'profile/avatar',
    'save' => 'profile/save',
	'search' => 'search/index',
	'addtag' => 'profile/addtag',
    'deletetag' => 'profile/deletetag',
	'more' => 'profile/more',
	'settings' => 'profile/settings',
    'profile/([0-9]+)' => 'profile/index/$1',
	'activate' => 'user/activate',
	'send_code' => 'user/send_code',
	'reset' => 'user/reset',
	'logout' => 'user/logout',
	'register' => 'user/register',
	'login' => 'user/login',
//	'.+' => 'error/index',
	'' => 'user/index',
);